name: flutter_visualise
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  audioplayers: ^4.1.0
  ffmpeg_kit_flutter: ^5.1.0
  fftea: ^1.3.1
  flutter:
    sdk: flutter
  flutter_audio_waveforms: ^1.2.1+8
  just_audio: ^0.9.34
  path_provider: ^2.0.15
  wav: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
